<center> <h1>Numerical Python (NumPy)</h1> </center><br><hr>

In [1]:
import numpy as np

## Creating 1D Arrays

In [2]:
l = [1,2,3]
x = np.array(l)
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
type(y)

numpy.ndarray

In [4]:
print(x.shape)
print(y.shape)
print(x.dtype)
y.dtype

(3,)
(3,)
int64


dtype('int64')

In [5]:
foo = np.array(['n','u','m','p','y'], dtype=np.str)
foo.dtype # {little-endian, unicode, 8-bit} 
                                            # https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

dtype('<U1')

In [6]:
n = np.arange(0, 30, 2) # create an array of numbers between [0,30) with an interval of 2
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [7]:
o = np.linspace(0, 10, 9) # create an array of 9 elements between [0,10]. Decide the interval according to n
o

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

## Creating 2D Arrays

In [8]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a.shape)
print(a.ndim)

(3, 3)
2


In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
p = np.ones((3,2), int)
p

array([[1, 1],
       [1, 1],
       [1, 1]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(3) # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.diag(np.array([1,2,3])) # Diagonal array

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [15]:
np.random.random((2,3))

array([[0.4211831 , 0.67693278, 0.04183296],
       [0.57816233, 0.42050396, 0.91320764]])

In [16]:
np.diag((10,99,44)).flatten()

array([10,  0,  0,  0, 99,  0,  0,  0, 44])

## Reshaping VS Resizing

In [17]:
n = n.reshape(3,5) # the product should match the number of total elements
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [18]:
o = np.linspace(0,10,9)
o.resize(3,3) # Inplace
o

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

### Stacking

In [78]:
np.stack([[1,2], [99,100], [-45, -47]], axis=0)#0)

array([[  1,   2],
       [ 99, 100],
       [-45, -47]])

In [74]:
np.vstack?
np.vstack([[1,2],[99,100],[-45,-47]])

array([[  1,   2],
       [ 99, 100],
       [-45, -47]])

In [71]:
np.hstack?
np.hstack([[1,2],[99,100],[-45,-47]])

array([  1,   2,  99, 100, -45, -47])

In [73]:
arr1=np.array([[1,2],[11,12]])
arr2=np.array([[3,4],[31,41]])
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [11, 12, 31, 41]])

In [77]:
arr3 = np.array([[1,11], [2,22], [3,33]])
arr4 = np.array([[2,22], [3,33], [4,44]])
np.vstack((arr3,arr4))

array([[ 1, 11],
       [ 2, 22],
       [ 3, 33],
       [ 2, 22],
       [ 3, 33],
       [ 4, 44]])

## Vectorized Operations

In [23]:
print("X:", x)
print("Y:", y)

X: [1 2 3]
Y: [4 5 6]


In [24]:
# Pointwise / Elementwise
print("X+Y:", x+y)
print("X*Y:", x*y)
print("X/Y:", x/y)
print("X**Y:", x**y)

X+Y: [5 7 9]
X*Y: [ 4 10 18]
X/Y: [0.25 0.4  0.5 ]
X**Y: [  1  32 729]


In [25]:
# Multiplication with a scalar
print(np.array([1,2,3]) * 3, "-- array * 3")
print("VS")
print(np.array([1,2,3] * 3), "-- list * 3")
print("VS")
print(np.repeat([1,2,3], 3), "-- repeat method of numpy array")

[3 6 9] -- array * 3
VS
[1 2 3 1 2 3 1 2 3] -- list * 3
VS
[1 1 1 2 2 2 3 3 3] -- repeat method of numpy array


In [26]:
# Dot Product
x.dot(y)

32

In [27]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

## Transposing

In [28]:
# Transpose
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [29]:
print(z.shape, z.T.shape)

(2, 3) (3, 2)


### Type casting

In [30]:
z.dtype

dtype('int64')

In [79]:
z = z.astype('f') # Casting into another data type
print(z)
z.dtype

[[ 4.  5.  6.]
 [16. 25. 36.]]


dtype('float32')

## 2D Axis

In [32]:
a = np.array([-4,-3,-1,5,19])
b = np.array([[1,99,20,31],[-1,-24,37,-13],[-7,11,49,4]])

In [33]:
print(a)
print("Max:", a.max())
print("Min:", a.min())
print("Mean:", a.mean())
print("Std:", a.std())
print("Index of Max Value:", a.argmax())
print("Max Value", a[a.argmax()])
print("Index of Min Value:", a.argmin())

[-4 -3 -1  5 19]
Max: 19
Min: -4
Mean: 3.2
Std: 8.49470423263812
Index of Max Value: 4
Max Value 19
Index of Min Value: 0


In [34]:
print(b, end='\n\n')

print("Max:", b.max())
print("Min:", b.min())
print("Mean:", b.mean())
print("Std:", b.std())
print("Index of Max Value:", b.argmax()) # Returns position of the flattened
print("Index of Min Value:", b.argmin())

print('\n\n-- ALONG AXIS 0 --')
print("Max:", b.max(axis=0))
print("Min:", b.min(axis=0))
print("Mean:", b.mean(axis=0))
print("Std:", b.std(axis=0))
print("Index of Max Value:", b.argmax(axis=0)) # Returns position of the flattened
print("Index of Min Value:", b.argmin(axis=0))

print('\n-- ALONG AXIS 1 --')
print("Max:", b.max(axis=1))
print("Min:", b.min(axis=1))
print("Mean:", b.mean(axis=1))
print("Std:", b.std(axis=1))
print("Index of Max Value:", b.argmax(axis=1)) # Returns position of the flattened
print("Index of Min Value:", b.argmin(axis=1))

[[  1  99  20  31]
 [ -1 -24  37 -13]
 [ -7  11  49   4]]

Max: 99
Min: -24
Mean: 17.25
Std: 32.00813698629355
Index of Max Value: 1
Index of Min Value: 5


-- ALONG AXIS 0 --
Max: [ 1 99 49 31]
Min: [ -7 -24  20 -13]
Mean: [-2.33333333 28.66666667 35.33333333  7.33333333]
Std: [ 3.39934634 51.74510175 11.8977122  18.11690432]
Index of Max Value: [0 0 2 0]
Index of Min Value: [2 1 0 1]

-- ALONG AXIS 1 --
Max: [99 37 49]
Min: [  1 -24  -7]
Mean: [37.75 -0.25 14.25]
Std: [36.95520938 22.99320552 21.0638909 ]
Index of Max Value: [1 2 2]
Index of Min Value: [0 1 0]


## Indexing & Slicing
#### Slicing => Viewing

In [35]:
a = np.arange(0,13,1)
a = a**2
# a = np.arange(13)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [36]:
a[0], a[4], a[0:3]

(0, 16, array([0, 1, 4]))

In [37]:
a[-4:]

array([ 81, 100, 121, 144])

In [38]:
a[-5::-2]

array([64, 36, 16,  4,  0])

In [80]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [84]:
print(r[2,2]) # Second row, second column
print(r[2][2])
print(r[2])
'''
    Notice the ',' usage while indexing as compared to [][] usage to access multidimensional lists
'''

14
14
[12 13 14 15 16 17]


"\n    Notice the ',' usage while indexing as compared to [][] usage to access multidimensional lists\n"

In [41]:
r[3, 3:]

array([21, 22, 23])

In [42]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [43]:
# Every second element from the last row
r[-1, ::2]

array([30, 32, 34])

## Conditonal Indexing (Index Arrays)

In [86]:
print(r[r>30])
print(r>30)

[31 32 33 34 35]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False  True  True  True  True  True]]


In [45]:
# Assigning the elements greater than 30 to a new value
r[r > 30] = 99
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [46]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [47]:
r2[0,0] = 100

In [48]:
r

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  99,  99,  99,  99,  99]])

### + vs +=

In [49]:
a = np.array([1,2,3,4])
b = a
a += np.array([1,1,1,1])  # inplace
print('a:', a)
print('b:', b)

a: [2 3 4 5]
b: [2 3 4 5]


In [50]:
a = np.array([1,2,3,4])
b = a
a = a + np.array([1,1,1,1])
print('a:', a)
print('b:', b)

a: [2 3 4 5]
b: [1 2 3 4]


## Copying

In [51]:
r2[:] = 0
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [52]:
rc = r.copy()
rc

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [53]:
rc[rc < 3] = 3

In [54]:
rc

array([[ 3,  3,  3,  3,  4,  5],
       [ 3,  3,  3,  9, 10, 11],
       [ 3,  3,  3, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [55]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

## Iterating

In [56]:
test = np.random.randint(0, 10, (4,3))
test

array([[0, 4, 0],
       [6, 0, 3],
       [1, 4, 8],
       [0, 7, 7]])

In [57]:
for row in test:
    print(row)

[0 4 0]
[6 0 3]
[1 4 8]
[0 7 7]


In [58]:
for index in range(len(test)):
    print("Row {} is {}".format(index, test[index]))

Row 0 is [0 4 0]
Row 1 is [6 0 3]
Row 2 is [1 4 8]
Row 3 is [0 7 7]


In [59]:
for i, row in enumerate(test):
        print("Row {} is {}".format(i, test[i]))

Row 0 is [0 4 0]
Row 1 is [6 0 3]
Row 2 is [1 4 8]
Row 3 is [0 7 7]


In [60]:
test2 = test**2
test2

array([[ 0, 16,  0],
       [36,  0,  9],
       [ 1, 16, 64],
       [ 0, 49, 49]])

In [61]:
for i,j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[0 4 0] + [ 0 16  0] = [ 0 20  0]
[6 0 3] + [36  0  9] = [42  0 12]
[1 4 8] + [ 1 16 64] = [ 2 20 72]
[0 7 7] + [ 0 49 49] = [ 0 56 56]
